
export enum ActionTypes {
    SET_USER = "SET_USER",
    SET_USER_LOADING = "SET_USER_LOADING",
    SET_USER_ERROR = "SET_USER_ERROR",
    CHNAGE_THEME = 'CHNAGE_THEME',
    CHECK_THEME = 'CHECK_THEME',
    CHECK_LANG = "CHECK_LANG",
    CHNAGE_LANG = "CHNAGE_LANG",
    LOGIN = 'LOGIN',
    CHECK_LOGIN = 'CHECK_LOGIN',
    LOGOUT = 'LOGOUT'
}