
export enum Route {
    WELCOME = "WELCOME",
    MODAL = "MODAL",
    USERSCREEN = "USERSCREEN",
    USERSCREEN_TAB = "USERSCREEN_TAB",
    APPSTACK = "APPSTACK",
    SETTINGS = "SETTINGS",
    SETTINGS_TAB = "SETTINGS_TAB",
    SELECTEDUSERSCREEN = "SELECTEDUSERSCREEN",
    LOGIN_SCREEN = "LOGIN_SCREEN"
}