
export enum Route {
    WELCOME = "WELCOME",
    MODAL = "MODAL",
    USER_SCREEN = "USER_SCREEN",
    USERSCREEN_TAB = "USERSCREEN_TAB",
    APPSTACK = "APPSTACK",
    SETTINGS = "SETTINGS",
    SETTINGS_TAB = "SETTINGS_TAB",
    SELECTED_USER_SCREEN = "SELECTED_USER_SCREEN",
    LOGIN_SCREEN = "LOGIN_SCREEN"
}